name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest
      - name: Notify Telex
        if: success()
        run: |
          curl -X POST \
          $TELEX_WEBHOOK \
          -H "accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{
          "event_name": "ci pipeline",
          "status": "success",
          "username": "GitHub Actions",
          "message": "Tests passed for ${{ github.event.pull_request }}",
          }' ${{ secrets.TELEX_WEBHOOK }}
      - name: Notify Telex
        if: failure()
        run: |
          curl -X POST \
          $TELEX_WEBHOOK \
          -H "accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{
          "event_name": "ci pipeline",
          "status": "failure",
          "username": "GitHub Actions",
          "message": "Tests failed for ${{ github.event_name }}",
          }'

  deploy:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 60

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/telex-integration
            git pull origin main
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload &